version: "3.7"

volumes:
  dbdata:

services:
  geospotter-service:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVICE_NAME: geospotter-service
      SERVICE_TAGS: dev
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_IDE_CONFIG: "serverName=localhost.local"
    volumes:
      - ./api:/var/www/html/geospotter
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /var/www/html/geospotter
    depends_on:
      - geospotter-db

  geospotter-db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./api:/var/www/html/geospotter
      - ./nginx/conf.d/geospotter.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - geospotter-service
